// שמות באנגלית לרשימת ספרי ההיכרות (src/starter-books.js), לממשק באנגלית: 'שם בעברית|מחבר' → [שם באנגלית, מחבר באנגלית].
// לספרים מתורגמים: השם שבו הספר ידוע באנגלית; לספרות עברית: שם המהדורה האנגלית (או תרגום של השם כשאין מהדורה).
export const STARTER_EN = {
  "סיפור על אהבה וחושך|עמוס עוז": ["A Tale of Love and Darkness", "Amos Oz"],
  "מיכאל שלי|עמוס עוז": ["My Michael", "Amos Oz"],
  "הבשורה על פי יהודה|עמוס עוז": ["Judas", "Amos Oz"],
  "הכלה המשוחררת|א.ב. יהושע": ["The Liberated Bride", "A. B. Yehoshua"],
  "מר מאני|א.ב. יהושע": ["Mr. Mani", "A. B. Yehoshua"],
  "המאהב|א.ב. יהושע": ["The Lover", "A. B. Yehoshua"],
  "השיבה מהודו|א.ב. יהושע": ["Open Heart", "A. B. Yehoshua"],
  "אשה בורחת מבשורה|דוד גרוסמן": ["To the End of the Land", "David Grossman"],
  "סוס אחד נכנס לבר|דוד גרוסמן": ["A Horse Walks into a Bar", "David Grossman"],
  "מישהו לרוץ איתו|דוד גרוסמן": ["Someone to Run With", "David Grossman"],
  "עיין ערך: אהבה|דוד גרוסמן": ["See Under: Love", "David Grossman"],
  "ארבעה בתים וגעגוע|אשכול נבו": ["Homesick", "Eshkol Nevo"],
  "נוילנד|אשכול נבו": ["Neuland", "Eshkol Nevo"],
  "שלוש קומות|אשכול נבו": ["Three Floors Up", "Eshkol Nevo"],
  "משאלה אחת ימינה|אשכול נבו": ["World Cup Wishes", "Eshkol Nevo"],
  "יונה ונער|מאיר שלו": ["A Pigeon and a Boy", "Meir Shalev"],
  "רומן רוסי|מאיר שלו": ["The Blue Mountain", "Meir Shalev"],
  "פונטנלה|מאיר שלו": ["Fontanelle", "Meir Shalev"],
  "בעל ואשה|צרויה שלו": ["Husband and Wife", "Zeruya Shalev"],
  "חצוצרה בואדי|סמי מיכאל": ["A Trumpet in the Wadi", "Sami Michael"],
  "ויקטוריה|סמי מיכאל": ["Victoria", "Sami Michael"],
  "תרנגול כפרות|אלי עמיר": ["Scapegoat", "Eli Amir"],
  "התגנבות יחידים|יהושע קנז": ["Infiltration", "Yehoshua Kenaz"],
  "גדר חיה|דורית רביניאן": ["All the Rivers", "Dorit Rabinyan"],
  "סיפור פשוט|ש\"י עגנון": ["A Simple Story", "S. Y. Agnon"],
  "תמול שלשום|ש\"י עגנון": ["Only Yesterday", "S. Y. Agnon"],
  "הוא הלך בשדות|משה שמיר": ["He Walked Through the Fields", "Moshe Shamir"],
  "מלכת היופי של ירושלים|שרית ישי-לוי": ["The Beauty Queen of Jerusalem", "Sarit Yishai-Levi"],
  "חוות החיות|ג'ורג' אורוול": ["Animal Farm", "George Orwell"],
  "אנה קרנינה|לב טולסטוי": ["Anna Karenina", "Leo Tolstoy"],
  "מלחמה ושלום|לב טולסטוי": ["War and Peace", "Leo Tolstoy"],
  "החטא ועונשו|פיודור דוסטויבסקי": ["Crime and Punishment", "Fyodor Dostoevsky"],
  "האחים קרמזוב|פיודור דוסטויבסקי": ["The Brothers Karamazov", "Fyodor Dostoevsky"],
  "גאווה ודעה קדומה|ג'יין אוסטן": ["Pride and Prejudice", "Jane Austen"],
  "מאה שנים של בדידות|גבריאל גרסיה מרקס": ["One Hundred Years of Solitude", "Gabriel García Márquez"],
  "אהבה בימי כולרה|גבריאל גרסיה מרקס": ["Love in the Time of Cholera", "Gabriel García Márquez"],
  "הזקן והים|ארנסט המינגוויי": ["The Old Man and the Sea", "Ernest Hemingway"],
  "למי צלצלו הפעמונים|ארנסט המינגוויי": ["For Whom the Bell Tolls", "Ernest Hemingway"],
  "גטסבי הגדול|פ. סקוט פיצג'רלד": ["The Great Gatsby", "F. Scott Fitzgerald"],
  "התפסן בשדה השיפון|ג'.ד. סלינג'ר": ["The Catcher in the Rye", "J. D. Salinger"],
  "להרוג ציפור מקננת|הארפר לי": ["To Kill a Mockingbird", "Harper Lee"],
  "הזר|אלבר קאמי": ["The Stranger", "Albert Camus"],
  "הדבר|אלבר קאמי": ["The Plague", "Albert Camus"],
  "המשפט|פרנץ קפקא": ["The Trial", "Franz Kafka"],
  "הגלגול|פרנץ קפקא": ["The Metamorphosis", "Franz Kafka"],
  "עלובי החיים|ויקטור הוגו": ["Les Misérables", "Victor Hugo"],
  "הרוזן ממונטה כריסטו|אלכסנדר דיומא": ["The Count of Monte Cristo", "Alexandre Dumas"],
  "ג'יין אייר|שרלוט ברונטה": ["Jane Eyre", "Charlotte Brontë"],
  "אנקת גבהים|אמילי ברונטה": ["Wuthering Heights", "Emily Brontë"],
  "מובי דיק|הרמן מלוויל": ["Moby-Dick", "Herman Melville"],
  "האמן ומרגריטה|מיכאיל בולגקוב": ["The Master and Margarita", "Mikhail Bulgakov"],
  "זורבה היווני|ניקוס קזנצאקיס": ["Zorba the Greek", "Nikos Kazantzakis"],
  "סידהרתה|הרמן הסה": ["Siddhartha", "Hermann Hesse"],
  "על עכברים ואנשים|ג'ון סטיינבק": ["Of Mice and Men", "John Steinbeck"],
  "לוליטה|ולדימיר נבוקוב": ["Lolita", "Vladimir Nabokov"],
  "מלכוד 22|ג'וזף הלר": ["Catch-22", "Joseph Heller"],
  "החברה הגאונה|אלנה פרנטה": ["My Brilliant Friend", "Elena Ferrante"],
  "יער נורווגי|הרוקי מורקמי": ["Norwegian Wood", "Haruki Murakami"],
  "קפקא על החוף|הרוקי מורקמי": ["Kafka on the Shore", "Haruki Murakami"],
  "1Q84|הרוקי מורקמי": ["1Q84", "Haruki Murakami"],
  "רודף העפיפונים|חאלד חוסייני": ["The Kite Runner", "Khaled Hosseini"],
  "אלף שמשות זוהרות|חאלד חוסייני": ["A Thousand Splendid Suns", "Khaled Hosseini"],
  "חיי פיי|יאן מרטל": ["Life of Pi", "Yann Martel"],
  "צל הרוח|קרלוס רואיס סאפון": ["The Shadow of the Wind", "Carlos Ruiz Zafón"],
  "איפה שהסרטנים שרים|דליה אוונס": ["Where the Crawdads Sing", "Delia Owens"],
  "אני לא מפחד|ניקולו אמאניטי": ["I'm Not Scared", "Niccolò Ammaniti"],
  "אנשים רגילים|סאלי רוני": ["Normal People", "Sally Rooney"],
  "חיים קטנים|האניה יאנאגיהארה": ["A Little Life", "Hanya Yanagihara"],
  "הדרך|קורמק מקארתי": ["The Road", "Cormac McCarthy"],
  "סטונר|ג'ון ויליאמס": ["Stoner", "John Williams"],
  "קרקס הלילה|ארין מורגנשטרן": ["The Night Circus", "Erin Morgenstern"],
  "אל תעזבי אותי|קאזואו אישיגורו": ["Never Let Me Go", "Kazuo Ishiguro"],
  "שארית היום|קאזואו אישיגורו": ["The Remains of the Day", "Kazuo Ishiguro"],
  "ילדי חצות|סלמאן רושדי": ["Midnight's Children", "Salman Rushdie"],
  "הצבע הסגול|אליס ווקר": ["The Color Purple", "Alice Walker"],
  "כפרה|איאן מקיואן": ["Atonement", "Ian McEwan"],
  "אמסטרדם|איאן מקיואן": ["Amsterdam", "Ian McEwan"],
  "על העיוורון|ז'וזה סאראמאגו": ["Blindness", "José Saramago"],
  "בית הרוחות|איזבל איינדה": ["The House of the Spirits", "Isabel Allende"],
  "כל החיים לפניו|רומן גארי": ["The Life Before Us", "Romain Gary"],
  "פאצ'ינקו|מין ג'ין לי": ["Pachinko", "Min Jin Lee"],
  "צופן דה וינצ'י|דן בראון": ["The Da Vinci Code", "Dan Brown"],
  "מלאכים ושדים|דן בראון": ["Angels & Demons", "Dan Brown"],
  "אינפרנו|דן בראון": ["Inferno", "Dan Brown"],
  "הסמל האבוד|דן בראון": ["The Lost Symbol", "Dan Brown"],
  "הנערה עם קעקוע הדרקון|סטיג לרסון": ["The Girl with the Dragon Tattoo", "Stieg Larsson"],
  "הנערה ששיחקה באש|סטיג לרסון": ["The Girl Who Played with Fire", "Stieg Larsson"],
  "הבחורה ברכבת|פולה הוקינס": ["The Girl on the Train", "Paula Hawkins"],
  "נעלמת|ג'יליאן פלין": ["Gone Girl", "Gillian Flynn"],
  "איש השלג|יו נסבו": ["The Snowman", "Jo Nesbø"],
  "רצח באוריינט אקספרס|אגתה כריסטי": ["Murder on the Orient Express", "Agatha Christie"],
  "ואז לא נשאר אף אחד|אגתה כריסטי": ["And Then There Were None", "Agatha Christie"],
  "רצח על הנילוס|אגתה כריסטי": ["Death on the Nile", "Agatha Christie"],
  "רצח רוג'ר אקרויד|אגתה כריסטי": ["The Murder of Roger Ackroyd", "Agatha Christie"],
  "הכלב של בני בסקרוויל|ארתור קונן דויל": ["The Hound of the Baskervilles", "Arthur Conan Doyle"],
  "שתיקת הכבשים|תומאס האריס": ["The Silence of the Lambs", "Thomas Harris"],
  "הדרקון האדום|תומאס האריס": ["Red Dragon", "Thomas Harris"],
  "המטופלת השקטה|אלכס מיכאלידס": ["The Silent Patient", "Alex Michaelides"],
  "שקרים קטנים גדולים|ליאן מוריארטי": ["Big Little Lies", "Liane Moriarty"],
  "תיק נעדר|דרור משעני": ["The Missing File", "D. A. Mishani"],
  "אפשרות של אלימות|דרור משעני": ["A Possibility of Violence", "D. A. Mishani"],
  "רצח בשבת בבוקר|בתיה גור": ["The Saturday Morning Murder", "Batya Gur"],
  "הפירמה|ג'ון גרישם": ["The Firm", "John Grisham"],
  "שם הוורד|אומברטו אקו": ["The Name of the Rose", "Umberto Eco"],
  "מועדון הרצח של יום חמישי|ריצ'רד אוסמן": ["The Thursday Murder Club", "Richard Osman"],
  "המשרתת|פרידה מקפאדן": ["The Housemaid", "Freida McFadden"],
  "אי המבודדים|דניס להיין": ["Shutter Island", "Dennis Lehane"],
  "עורך הדין מהלינקולן|מייקל קונלי": ["The Lincoln Lawyer", "Michael Connelly"],
  "אישה בחלון|א.ג'. פין": ["The Woman in the Window", "A. J. Finn"],
  "הארי פוטר ואבן החכמים|ג'.ק. רולינג": ["Harry Potter and the Philosopher's Stone", "J. K. Rowling"],
  "הארי פוטר וחדר הסודות|ג'.ק. רולינג": ["Harry Potter and the Chamber of Secrets", "J. K. Rowling"],
  "הארי פוטר והאסיר מאזקבאן|ג'.ק. רולינג": ["Harry Potter and the Prisoner of Azkaban", "J. K. Rowling"],
  "הארי פוטר וגביע האש|ג'.ק. רולינג": ["Harry Potter and the Goblet of Fire", "J. K. Rowling"],
  "הארי פוטר ואוצרות המוות|ג'.ק. רולינג": ["Harry Potter and the Deathly Hallows", "J. K. Rowling"],
  "ההוביט|ג'.ר.ר. טולקין": ["The Hobbit", "J. R. R. Tolkien"],
  "שר הטבעות: אחוות הטבעת|ג'.ר.ר. טולקין": ["The Fellowship of the Ring", "J. R. R. Tolkien"],
  "שר הטבעות: שני הצריחים|ג'.ר.ר. טולקין": ["The Two Towers", "J. R. R. Tolkien"],
  "שר הטבעות: שובו של המלך|ג'.ר.ר. טולקין": ["The Return of the King", "J. R. R. Tolkien"],
  "משחקי הכס|ג'ורג' ר.ר. מרטין": ["A Game of Thrones", "George R. R. Martin"],
  "התנגשות המלכים|ג'ורג' ר.ר. מרטין": ["A Clash of Kings", "George R. R. Martin"],
  "האריה, המכשפה וארון הבגדים|ק.ס. לואיס": ["The Lion, the Witch and the Wardrobe", "C. S. Lewis"],
  "שם הרוח|פטריק רותפוס": ["The Name of the Wind", "Patrick Rothfuss"],
  "הסיפור שאינו נגמר|מיכאל אנדה": ["The Neverending Story", "Michael Ende"],
  "מומו|מיכאל אנדה": ["Momo", "Michael Ende"],
  "הקוסם מארץ ים|אורסולה לה גווין": ["A Wizard of Earthsea", "Ursula K. Le Guin"],
  "פרסי ג'קסון וגנב הברק|ריק ריירדן": ["The Lightning Thief", "Rick Riordan"],
  "אבק כוכבים|ניל גיימן": ["Stardust", "Neil Gaiman"],
  "אלים אמריקאים|ניל גיימן": ["American Gods", "Neil Gaiman"],
  "אוקיינוס בקצה המשעול|ניל גיימן": ["The Ocean at the End of the Lane", "Neil Gaiman"],
  "קורליין|ניל גיימן": ["Coraline", "Neil Gaiman"],
  "מצפן הזהב|פיליפ פולמן": ["Northern Lights", "Philip Pullman"],
  "אראגון|כריסטופר פאוליני": ["Eragon", "Christopher Paolini"],
  "עיר של עצמות|קסנדרה קלייר": ["City of Bones", "Cassandra Clare"],
  "דמדומים|סטפני מאייר": ["Twilight", "Stephenie Meyer"],
  "צל ועצם|לי ברדוגו": ["Shadow and Bone", "Leigh Bardugo"],
  "הבית של מיס פרגרין לילדים משונים|רנסום ריגס": ["Miss Peregrine's Home for Peculiar Children", "Ransom Riggs"],
  "ג'ונתן סטריינג' ומר נורל|סוזנה קלארק": ["Jonathan Strange & Mr Norrell", "Susanna Clarke"],
  "1984|ג'ורג' אורוול": ["Nineteen Eighty-Four", "George Orwell"],
  "עולם חדש מופלא|אלדוס האקסלי": ["Brave New World", "Aldous Huxley"],
  "פרנהייט 451|ריי ברדבורי": ["Fahrenheit 451", "Ray Bradbury"],
  "סיפורה של שפחה|מרגרט אטווד": ["The Handmaid's Tale", "Margaret Atwood"],
  "התפוז המכני|אנתוני ברג'ס": ["A Clockwork Orange", "Anthony Burgess"],
  "משחקי הרעב|סוזן קולינס": ["The Hunger Games", "Suzanne Collins"],
  "דיונה|פרנק הרברט": ["Dune", "Frank Herbert"],
  "פרויקט הייל מרי|אנדי ויר": ["Project Hail Mary", "Andy Weir"],
  "לבד על מאדים|אנדי ויר": ["The Martian", "Andy Weir"],
  "המשחק של אנדר|אורסון סקוט קארד": ["Ender's Game", "Orson Scott Card"],
  "אני, רובוט|אייזק אסימוב": ["I, Robot", "Isaac Asimov"],
  "המוסד|אייזק אסימוב": ["Foundation", "Isaac Asimov"],
  "הבעיה של שלושת הגופים|ליו צ'יסין": ["The Three-Body Problem", "Liu Cixin"],
  "מכונת הזמן|ה.ג. וולס": ["The Time Machine", "H. G. Wells"],
  "מלחמת העולמות|ה.ג. וולס": ["The War of the Worlds", "H. G. Wells"],
  "האיש הבלתי נראה|ה.ג. וולס": ["The Invisible Man", "H. G. Wells"],
  "ניורומנסר|ויליאם גיבסון": ["Neuromancer", "William Gibson"],
  "האם אנדרואידים חולמים על כבשים חשמליות?|פיליפ ק. דיק": ["Do Androids Dream of Electric Sheep?", "Philip K. Dick"],
  "עשרים אלף מיל מתחת למים|ז'ול ורן": ["Twenty Thousand Leagues Under the Seas", "Jules Verne"],
  "מסע אל מרכז כדור הארץ|ז'ול ורן": ["Journey to the Center of the Earth", "Jules Verne"],
  "פרנקנשטיין|מרי שלי": ["Frankenstein", "Mary Shelley"],
  "הרץ במבוך|ג'יימס דאשנר": ["The Maze Runner", "James Dashner"],
  "שחקן מספר אחת|ארנסט קליין": ["Ready Player One", "Ernest Cline"],
  "סולאריס|סטניסלב לם": ["Solaris", "Stanisław Lem"],
  "היפריון|דן סימונס": ["Hyperion", "Dan Simmons"],
  "פרחים לאלג'רנון|דניאל קיז": ["Flowers for Algernon", "Daniel Keyes"],
  "אנחנו|יבגני זמיאטין": ["We", "Yevgeny Zamyatin"],
  "הדלת אל הקיץ|רוברט היינליין": ["The Door into Summer", "Robert A. Heinlein"],
  "אני לפנייך|ג'וג'ו מויס": ["Me Before You", "Jojo Moyes"],
  "אחרייך|ג'וג'ו מויס": ["After You", "Jojo Moyes"],
  "יום אחד|דייוויד ניקולס": ["One Day", "David Nicholls"],
  "אשמת הכוכבים|ג'ון גרין": ["The Fault in Our Stars", "John Green"],
  "זה נגמר איתנו|קולין הובר": ["It Ends with Us", "Colleen Hoover"],
  "זה מתחיל איתנו|קולין הובר": ["It Starts with Us", "Colleen Hoover"],
  "שבעת בעליה של אוולין הוגו|טיילור ג'נקינס ריד": ["The Seven Husbands of Evelyn Hugo", "Taylor Jenkins Reid"],
  "היומן|ניקולס ספארקס": ["The Notebook", "Nicholas Sparks"],
  "מסר בבקבוק|ניקולס ספארקס": ["Message in a Bottle", "Nicholas Sparks"],
  "הדוכס ואני|ג'וליה קווין": ["The Duke and I", "Julia Quinn"],
  "חלף עם הרוח|מרגרט מיטשל": ["Gone with the Wind", "Margaret Mitchell"],
  "רבקה|דפנה דה מורייה": ["Rebecca", "Daphne du Maurier"],
  "אשת הנוסע בזמן|אודרי ניפנגר": ["The Time Traveler's Wife", "Audrey Niffenegger"],
  "היגיון ורגישות|ג'יין אוסטן": ["Sense and Sensibility", "Jane Austen"],
  "אמה|ג'יין אוסטן": ["Emma", "Jane Austen"],
  "שכנוע|ג'יין אוסטן": ["Persuasion", "Jane Austen"],
  "חיי אהבה|צרויה שלו": ["Love Life", "Zeruya Shalev"],
  "הגשרים של מחוז מדיסון|רוברט ג'יימס וולר": ["The Bridges of Madison County", "Robert James Waller"],
  "קרא לי בשמך|אנדרה אסימן": ["Call Me by Your Name", "André Aciman"],
  "חמישים גוונים של אפור|א.ל. ג'יימס": ["Fifty Shades of Grey", "E. L. James"],
  "כמו מים לשוקולד|לאורה אסקיבל": ["Like Water for Chocolate", "Laura Esquivel"],
  "ברוקלין|קולם טויבין": ["Brooklyn", "Colm Tóibín"],
  "הפצוע האנגלי|מייקל אונדאטיה": ["The English Patient", "Michael Ondaatje"],
  "סיפור אהבה|אריך סגל": ["Love Story", "Erich Segal"],
  "דוקטור ז'יוואגו|בוריס פסטרנק": ["Doctor Zhivago", "Boris Pasternak"],
  "זרה|דיאנה גבלדון": ["Outlander", "Diana Gabaldon"],
  "עמודי תבל|קן פולט": ["The Pillars of the Earth", "Ken Follett"],
  "עולם ללא סוף|קן פולט": ["World Without End", "Ken Follett"],
  "נפילתם של ענקים|קן פולט": ["Fall of Giants", "Ken Follett"],
  "וולף הול|הילארי מנטל": ["Wolf Hall", "Hilary Mantel"],
  "שוגון|ג'יימס קלאוול": ["Shōgun", "James Clavell"],
  "טאי-פן|ג'יימס קלאוול": ["Tai-Pan", "James Clavell"],
  "הנערה עם עגיל הפנינה|טרייסי שבלייה": ["Girl with a Pearl Earring", "Tracy Chevalier"],
  "האוהל האדום|אניטה דיאמנט": ["The Red Tent", "Anita Diamant"],
  "זיכרונותיה של גיישה|ארתור גולדן": ["Memoirs of a Geisha", "Arthur Golden"],
  "כל האור שאיננו רואים|אנתוני דואר": ["All the Light We Cannot See", "Anthony Doerr"],
  "הזמיר|קריסטין האנה": ["The Nightingale", "Kristin Hannah"],
  "לבד בברלין|הנס פאלאדה": ["Alone in Berlin", "Hans Fallada"],
  "אהבת ציון|אברהם מאפו": ["The Love of Zion", "Abraham Mapu"],
  "אקסודוס|לאון יוריס": ["Exodus", "Leon Uris"],
  "שלושת המוסקטרים|אלכסנדר דיומא": ["The Three Musketeers", "Alexandre Dumas"],
  "המלכה מרגו|אלכסנדר דיומא": ["Queen Margot", "Alexandre Dumas"],
  "איוונהו|וולטר סקוט": ["Ivanhoe", "Walter Scott"],
  "בן חור|לו וואלאס": ["Ben-Hur", "Lew Wallace"],
  "אני, קלאודיוס|רוברט גרייבס": ["I, Claudius", "Robert Graves"],
  "סיפור על שתי ערים|צ'ארלס דיקנס": ["A Tale of Two Cities", "Charles Dickens"],
  "אחרון המוהיקנים|ג'יימס פנימור קופר": ["The Last of the Mohicans", "James Fenimore Cooper"],
  "בית הקברות בפראג|אומברטו אקו": ["The Prague Cemetery", "Umberto Eco"],
  "שמי אדום|אורהן פאמוק": ["My Name Is Red", "Orhan Pamuk"],
  "הקתדרלה של הים|אילדפונסו פלקונס": ["Cathedral of the Sea", "Ildefonso Falcones"],
  "הגנרל במבוך שלו|גבריאל גרסיה מרקס": ["The General in His Labyrinth", "Gabriel García Márquez"],
  "יסמין|אלי עמיר": ["Jasmine", "Eli Amir"],
  "סמטת השקדיות בעומריג'אן|דורית רביניאן": ["Persian Brides", "Dorit Rabinyan"],
  "אנשים טובים|ניר ברעם": ["Good People", "Nir Baram"],
  "יומנה של אנה פרנק|אנה פרנק": ["The Diary of a Young Girl", "Anne Frank"],
  "הלילה|אלי ויזל": ["Night", "Elie Wiesel"],
  "הזהו אדם?|פרימו לוי": ["If This Is a Man", "Primo Levi"],
  "האדם מחפש משמעות|ויקטור פרנקל": ["Man's Search for Meaning", "Viktor Frankl"],
  "המקעקע מאושוויץ|הת'ר מוריס": ["The Tattooist of Auschwitz", "Heather Morris"],
  "הילד בפיג'מה המפוספסת|ג'ון בוין": ["The Boy in the Striped Pyjamas", "John Boyne"],
  "סלמנדרה|ק. צטניק": ["Salamandra", "Ka-Tzetnik 135633"],
  "בית הבובות|ק. צטניק": ["House of Dolls", "Ka-Tzetnik 135633"],
  "רשימת שינדלר|תומאס קנילי": ["Schindler's List", "Thomas Keneally"],
  "מאוס|ארט שפיגלמן": ["Maus", "Art Spiegelman"],
  "האי ברחוב הציפורים|אורי אורלב": ["The Island on Bird Street", "Uri Orlev"],
  "רוץ, ילד, רוץ|אורי אורלב": ["Run, Boy, Run", "Uri Orlev"],
  "חיילי עופרת|אורי אורלב": ["The Lead Soldiers", "Uri Orlev"],
  "גנבת הספרים|מרקוס זוסאק": ["The Book Thief", "Markus Zusak"],
  "הקורא|ברנהרד שלינק": ["The Reader", "Bernhard Schlink"],
  "מילה 18|לאון יוריס": ["Mila 18", "Leon Uris"],
  "הספרנית מאושוויץ|אנטוניו איטורבה": ["The Librarian of Auschwitz", "Antonio Iturbe"],
  "המפתח של שרה|טטיאנה דה רוניי": ["Sarah's Key", "Tatiana de Rosnay"],
  "אדם בן כלב|יורם קניוק": ["Adam Resurrected", "Yoram Kaniuk"],
  "הפסנתרן|ולדיסלב שפילמן": ["The Pianist", "Władysław Szpilman"],
  "הבחירה|אדית אגר": ["The Choice", "Edith Eger"],
  "שואה שלנו|אמיר גוטפרוינד": ["Our Holocaust", "Amir Gutfreund"],
  "באדנהיים עיר נופש|אהרן אפלפלד": ["Badenheim 1939", "Aharon Appelfeld"],
  "סיפור חיים|אהרן אפלפלד": ["The Story of a Life", "Aharon Appelfeld"],
  "יעקב השקרן|יורק בקר": ["Jacob the Liar", "Jurek Becker"],
  "הבחירה של סופי|ויליאם סטיירון": ["Sophie's Choice", "William Styron"],
  "בלי גורל|אימרה קרטס": ["Fatelessness", "Imre Kertész"],
  "אייכמן בירושלים|חנה ארנדט": ["Eichmann in Jerusalem", "Hannah Arendt"],
  "קיצור תולדות האנושות|יובל נח הררי": ["Sapiens", "Yuval Noah Harari"],
  "ההיסטוריה של המחר|יובל נח הררי": ["Homo Deus", "Yuval Noah Harari"],
  "21 שיעורים למאה ה-21|יובל נח הררי": ["21 Lessons for the 21st Century", "Yuval Noah Harari"],
  "נקסוס|יובל נח הררי": ["Nexus", "Yuval Noah Harari"],
  "רובים, חיידקים ופלדה|ג'ארד דיימונד": ["Guns, Germs, and Steel", "Jared Diamond"],
  "לחשוב מהר, לחשוב לאט|דניאל כהנמן": ["Thinking, Fast and Slow", "Daniel Kahneman"],
  "רעש|דניאל כהנמן": ["Noise", "Daniel Kahneman"],
  "פריקונומיקס|סטיבן לוויט": ["Freakonomics", "Steven D. Levitt and Stephen J. Dubner"],
  "אומת הסטארט-אפ|דן סינור ושאול זינגר": ["Start-up Nation", "Dan Senor and Saul Singer"],
  "קיצור תולדות הזמן|סטיבן הוקינג": ["A Brief History of Time", "Stephen Hawking"],
  "הגן האנוכי|ריצ'רד דוקינס": ["The Selfish Gene", "Richard Dawkins"],
  "יש אלוהים?|ריצ'רד דוקינס": ["The God Delusion", "Richard Dawkins"],
  "נקודת המפנה|מלקולם גלדוול": ["The Tipping Point", "Malcolm Gladwell"],
  "חריגים|מלקולם גלדוול": ["Outliers", "Malcolm Gladwell"],
  "הברבור השחור|נסים ניקולס טאלב": ["The Black Swan", "Nassim Nicholas Taleb"],
  "לא רציונלי ולא במקרה|דן אריאלי": ["Predictably Irrational", "Dan Ariely"],
  "הגן: היסטוריה אינטימית|סידהרתה מוקרג'י": ["The Gene: An Intimate History", "Siddhartha Mukherjee"],
  "קיסר כל המחלות|סידהרתה מוקרג'י": ["The Emperor of All Maladies", "Siddhartha Mukherjee"],
  "חייה האלמותיים של הנרייטה לאקס|רבקה סקלוט": ["The Immortal Life of Henrietta Lacks", "Rebecca Skloot"],
  "קוסמוס|קרל סייגן": ["Cosmos", "Carl Sagan"],
  "קיצור תולדות כמעט הכל|ביל ברייסון": ["A Short History of Nearly Everything", "Bill Bryson"],
  "הנסיך|ניקולו מקיאוולי": ["The Prince", "Niccolò Machiavelli"],
  "אמנות המלחמה|סון טסו": ["The Art of War", "Sun Tzu"],
  "המלאכים הטובים של טבענו|סטיבן פינקר": ["The Better Angels of Our Nature", "Steven Pinker"],
  "למה אנחנו ישנים|מתיו ווקר": ["Why We Sleep", "Matthew Walker"],
  "מדינת היהודים|בנימין זאב הרצל": ["The Jewish State", "Theodor Herzl"],
  "ירושלים: ביוגרפיה|סיימון סבג מונטיפיורי": ["Jerusalem: The Biography", "Simon Sebag Montefiore"],
  "החיים הסודיים של העצים|פטר וולבן": ["The Hidden Life of Trees", "Peter Wohlleben"],
  "סטיב ג'ובס|וולטר אייזקסון": ["Steve Jobs", "Walter Isaacson"],
  "אילון מאסק|וולטר אייזקסון": ["Elon Musk", "Walter Isaacson"],
  "איינשטיין: חייו ועולמו|וולטר אייזקסון": ["Einstein: His Life and Universe", "Walter Isaacson"],
  "לאונרדו דה וינצ'י|וולטר אייזקסון": ["Leonardo da Vinci", "Walter Isaacson"],
  "הסיפור שלי|מישל אובמה": ["Becoming", "Michelle Obama"],
  "ארץ מובטחת|ברק אובמה": ["A Promised Land", "Barack Obama"],
  "חלומות מאבי|ברק אובמה": ["Dreams from My Father", "Barack Obama"],
  "חיי|גולדה מאיר": ["My Life", "Golda Meir"],
  "פנקס שירות|יצחק רבין": ["The Rabin Memoirs", "Yitzhak Rabin"],
  "מכתבי יוני|יונתן נתניהו": ["Self-Portrait of a Hero", "Jonathan Netanyahu"],
  "היינו העתיד|יעל נאמן": ["We Were the Future", "Yael Neeman"],
  "אני מלאלה|מלאלה יוסופזאי": ["I Am Malala", "Malala Yousafzai"],
  "כשהנשימה נעשית אוויר|פול קלאניתי": ["When Breath Becomes Air", "Paul Kalanithi"],
  "המחונכת|טארה וסטובר": ["Educated", "Tara Westover"],
  "הדרך הארוכה לחירות|נלסון מנדלה": ["Long Walk to Freedom", "Nelson Mandela"],
  "אני נוג'וד, בת 10 וגרושה|נוג'וד עלי": ["I Am Nujood, Age 10 and Divorced", "Nujood Ali"],
  "יומני אופנוע|ארנסטו צ'ה גווארה": ["The Motorcycle Diaries", "Ernesto Che Guevara"],
  "אפר של אנג'לה|פרנק מקורט": ["Angela's Ashes", "Frank McCourt"],
  "מכתבים לתיאו|וינסנט ואן גוך": ["Letters to Theo", "Vincent van Gogh"],
  "אל תוך הפרא|ג'ון קרקאואר": ["Into the Wild", "Jon Krakauer"],
  "אל האוויר הדליל|ג'ון קרקאואר": ["Into Thin Air", "Jon Krakauer"],
  "שלוש כוסות תה|גרג מורטנסון": ["Three Cups of Tea", "Greg Mortenson"],
  "החיים שלי|ביל קלינטון": ["My Life", "Bill Clinton"],
  "הפרפר ופעמון הצלילה|ז'אן-דומיניק בובי": ["The Diving Bell and the Butterfly", "Jean-Dominique Bauby"],
  "בלתי שביר|לורה הילנברנד": ["Unbroken", "Laura Hillenbrand"],
  "האיש שלנו בדמשק|אלי בן חנן": ["Our Man in Damascus", "Eli Ben-Hanan"],
  "המילטון|רון צ'רנו": ["Alexander Hamilton", "Ron Chernow"],
  "כוחו של הרגע הזה|אקהרט טולה": ["The Power of Now", "Eckhart Tolle"],
  "האמנות העדינה של לא לתת זין|מארק מנסון": ["The Subtle Art of Not Giving a F*ck", "Mark Manson"],
  "חמש שפות האהבה|גארי צ'פמן": ["The 5 Love Languages", "Gary Chapman"],
  "אינטליגנציה רגשית|דניאל גולמן": ["Emotional Intelligence", "Daniel Goleman"],
  "ארבע ההסכמות|דון מיגל רואיז": ["The Four Agreements", "Don Miguel Ruiz"],
  "הסוד|רונדה ברן": ["The Secret", "Rhonda Byrne"],
  "הנביא|ג'ובראן ח'ליל ג'ובראן": ["The Prophet", "Kahlil Gibran"],
  "הגוף זוכר הכול|בסל ון דר קולק": ["The Body Keeps the Score", "Bessel van der Kolk"],
  "האומץ להיות לא אהוב|אייצ'ירו קישימי": ["The Courage to Be Disliked", "Ichiro Kishimi and Fumitake Koga"],
  "הנזיר שמכר את הפרארי שלו|רובין שארמה": ["The Monk Who Sold His Ferrari", "Robin Sharma"],
  "הרגלים אטומיים|ג'יימס קליר": ["Atomic Habits", "James Clear"],
  "כוחו של ההרגל|צ'ארלס דוהיג": ["The Power of Habit", "Charles Duhigg"],
  "7 ההרגלים של אנשים אפקטיביים במיוחד|סטיבן קובי": ["The 7 Habits of Highly Effective People", "Stephen R. Covey"],
  "אבא עשיר, אבא עני|רוברט קיוסאקי": ["Rich Dad Poor Dad", "Robert T. Kiyosaki"],
  "איך לרכוש חברים ולהשפיע על אנשים|דייל קרנגי": ["How to Win Friends and Influence People", "Dale Carnegie"],
  "שקט: כוחם של המופנמים|סוזן קיין": ["Quiet", "Susan Cain"],
  "גריט|אנג'לה דאקוורת'": ["Grit", "Angela Duckworth"],
  "מיינדסט|קרול דואק": ["Mindset", "Carol S. Dweck"],
  "האיש שחשב שאשתו היא כובע|אוליבר סאקס": ["The Man Who Mistook His Wife for a Hat", "Oliver Sacks"],
  "אמנות האהבה|אריך פרום": ["The Art of Loving", "Erich Fromm"],
  "להעז בגדול|ברנה בראון": ["Daring Greatly", "Brené Brown"],
  "חשוב והתעשר|נפוליאון היל": ["Think and Grow Rich", "Napoleon Hill"],
  "אכול את הצפרדע|בריאן טרייסי": ["Eat That Frog!", "Brian Tracy"],
  "הגיגים|מרקוס אורליוס": ["Meditations", "Marcus Aurelius"],
  "שבוע עבודה של 4 שעות|טים פריס": ["The 4-Hour Workweek", "Tim Ferriss"],
  "עבודה עמוקה|קאל ניופורט": ["Deep Work", "Cal Newport"],
  "השפעה|רוברט צ'לדיני": ["Influence", "Robert B. Cialdini"],
  "איקיגאי|הקטור גרסיה": ["Ikigai", "Héctor García and Francesc Miralles"],
  "חסמבה|יגאל מוסינזון": ["Hasamba", "Yigal Mossinson"],
  "שמונה בעקבות אחד|ימימה אבידר-טשרנוביץ": ["Eight in Pursuit of One", "Yemima Avidar-Tchernovitz"],
  "דני דין הרואה ואינו נראה|און שריג": ["Danny Din, the Invisible Boy", "On Sarig"],
  "הבכור לבית אבא|דבורה עומר": ["The Firstborn of His Father's House", "Devorah Omer"],
  "סומכי|עמוס עוז": ["Soumchi", "Amos Oz"],
  "דירה להשכיר|לאה גולדברג": ["Apartment for Rent", "Leah Goldberg"],
  "המלך מתיא הראשון|יאנוש קורצ'אק": ["King Matt the First", "Janusz Korczak"],
  "הנסיך הקטן|אנטואן דה סנט-אכזופרי": ["The Little Prince", "Antoine de Saint-Exupéry"],
  "פו הדב|א.א. מילן": ["Winnie-the-Pooh", "A. A. Milne"],
  "אליס בארץ הפלאות|לואיס קרול": ["Alice's Adventures in Wonderland", "Lewis Carroll"],
  "מטילדה|רואלד דאל": ["Matilda", "Roald Dahl"],
  "צ'רלי והשוקולדה|רואלד דאל": ["Charlie and the Chocolate Factory", "Roald Dahl"],
  "אן מהחווה הירוקה|לוסי מוד מונטגומרי": ["Anne of Green Gables", "L. M. Montgomery"],
  "נשים קטנות|לואיזה מיי אולקוט": ["Little Women", "Louisa May Alcott"],
  "יומנו של חנון|ג'ף קיני": ["Diary of a Wimpy Kid", "Jeff Kinney"],
  "הנותן|לויס לורי": ["The Giver", "Lois Lowry"],
  "פלא|ר.ג'. פלאסיו": ["Wonder", "R. J. Palacio"],
  "אמיל והבלשים|אריך קסטנר": ["Emil and the Detectives", "Erich Kästner"],
  "עולמה של סופי|יוסטיין גורדר": ["Sophie's World", "Jostein Gaarder"],
  "אי המטמון|רוברט לואיס סטיבנסון": ["Treasure Island", "Robert Louis Stevenson"],
  "הגן הנעלם|פרנסס הודג'סון ברנט": ["The Secret Garden", "Frances Hodgson Burnett"],
  "היידי|יוהנה שפירי": ["Heidi", "Johanna Spyri"],
  "פינוקיו|קרלו קולודי": ["The Adventures of Pinocchio", "Carlo Collodi"],
  "פיטר פן|ג'יימס מתיו בארי": ["Peter Pan", "J. M. Barrie"],
  "הרפתקאות תום סוייר|מארק טוויין": ["The Adventures of Tom Sawyer", "Mark Twain"],
  "הנסיך והקבצן|מארק טוויין": ["The Prince and the Pauper", "Mark Twain"],
  "רובינזון קרוזו|דניאל דפו": ["Robinson Crusoe", "Daniel Defoe"],
  "הילדים מרחוב פאל|פרנץ מולנאר": ["The Paul Street Boys", "Ferenc Molnár"],
  "שלושה בסירה אחת|ג'רום ק. ג'רום": ["Three Men in a Boat", "Jerome K. Jerome"],
  "החייל האמיץ שווייק|יארוסלב האשק": ["The Good Soldier Švejk", "Jaroslav Hašek"],
  "היומן הסודי של אדריאן מול|סו טאונסנד": ["The Secret Diary of Adrian Mole, Aged 13¾", "Sue Townsend"],
  "מדריך הטרמפיסט לגלקסיה|דאגלס אדמס": ["The Hitchhiker's Guide to the Galaxy", "Douglas Adams"],
  "צבע הקסם|טרי פראצ'ט": ["The Colour of Magic", "Terry Pratchett"],
  "בשורות טובות|טרי פראצ'ט וניל גיימן": ["Good Omens", "Terry Pratchett and Neil Gaiman"],
  "דון קישוט|מיגל דה סרוואנטס": ["Don Quixote", "Miguel de Cervantes"],
  "העולם הקטן של דון קמילו|ג'ובאני גוארסקי": ["The Little World of Don Camillo", "Giovannino Guareschi"],
  "הרפתקאות הברון מינכהאוזן|רודולף אריך רספה": ["The Surprising Adventures of Baron Munchausen", "Rudolf Erich Raspe"],
  "תופעות לוואי|וודי אלן": ["Side Effects", "Woody Allen"],
  "טוביה החולב|שלום עליכם": ["Tevye the Dairyman", "Sholem Aleichem"],
  "מוטל בן פייסי החזן|שלום עליכם": ["Motl, the Cantor's Son", "Sholem Aleichem"],
  "מסעות בנימין השלישי|מנדלי מוכר ספרים": ["The Travels of Benjamin the Third", "Mendele Mocher Sforim"],
  "סליחה שניצחנו|אפרים קישון": ["So Sorry We Won!", "Ephraim Kishon"],
  "ילקוט הכזבים|דן בן אמוץ וחיים חפר": ["The Bag of Lies", "Dan Ben-Amotz and Haim Hefer"],
  "צינורות|אתגר קרת": ["Pipelines", "Etgar Keret"],
  "פתאום דפיקה בדלת|אתגר קרת": ["Suddenly, a Knock on the Door", "Etgar Keret"],
  "הקייטנה של כנלר|אתגר קרת": ["Kneller's Happy Campers", "Etgar Keret"],
  "סוזאנה הבוכייה|אלונה קמחי": ["Weeping Susannah", "Alona Kimhi"],
  "אבא עושה בושות|מאיר שלו": ["My Father Always Embarrasses Me", "Meir Shalev"],
  "הכבש השישה עשר|יהונתן גפן": ["The Sixteenth Lamb", "Yehonatan Geffen"],
  "הזקן שיצא מהחלון ונעלם|יונס יונסון": ["The Hundred-Year-Old Man Who Climbed Out of the Window and Disappeared", "Jonas Jonasson"],
  "האנאלפביתית שידעה חשבון|יונס יונסון": ["The Girl Who Saved the King of Sweden", "Jonas Jonasson"],
  "אנשים חרדים|פרדריק בקמן": ["Anxious People", "Fredrik Backman"],
  "סבתא שלי מבקשת להגיד לך שהיא מצטערת|פרדריק בקמן": ["My Grandmother Asked Me to Tell You She's Sorry", "Fredrik Backman"],
  "בריט-מארי הייתה כאן|פרדריק בקמן": ["Britt-Marie Was Here", "Fredrik Backman"],
  "על ילד|ניק הורנבי": ["About a Boy", "Nick Hornby"],
  "המלכה ואני|סו טאונסנד": ["The Queen and I", "Sue Townsend"],
  "איש אחד ושמו אובה|פרדריק בקמן": ["A Man Called Ove", "Fredrik Backman"],
  "ספריית חצות|מאט הייג": ["The Midnight Library", "Matt Haig"],
  "אלינור אוליפנט בסדר גמור|גייל האניפמן": ["Eleanor Oliphant Is Completely Fine", "Gail Honeyman"],
  "האלכימאי|פאולו קואלו": ["The Alchemist", "Paulo Coelho"],
  "יומנה של ברידג'ט ג'ונס|הלן פילדינג": ["Bridget Jones's Diary", "Helen Fielding"],
  "P.S. אני אוהבת אותך|ססיליה אהרן": ["P.S. I Love You", "Cecelia Ahern"],
  "לאכול, להתפלל, לאהוב|אליזבת גילברט": ["Eat, Pray, Love", "Elizabeth Gilbert"],
  "שנה בפרובאנס|פיטר מייל": ["A Year in Provence", "Peter Mayle"],
  "שוקולד|ג'ואן האריס": ["Chocolat", "Joanne Harris"],
  "בית הקפה בקצה העולם|ג'ון סטרלקי": ["The Why Café", "John Strelecky"],
  "פרויקט רוזי|גראם סימסיון": ["The Rosie Project", "Graeme Simsion"],
  "אחת ועוד אחת|ג'וג'ו מויס": ["One Plus One", "Jojo Moyes"],
  "מאה ימים של אושר|פאוסטו ברידזי": ["One Hundred Days of Happiness", "Fausto Brizzi"],
  "היומן הסודי של הנדריק חרון|הנדריק חרון": ["The Secret Diary of Hendrik Groen, 83¼ Years Old", "Hendrik Groen"]
};
